name: Pull image from docker hub
description: Pull an image from docker hub
runs:
  using: composite
  steps:
    - name: "docker pull image"
      shell: bash
      run: |
        /bin/bash -x .github/actions/pullcontainer/pullcontainer.sh
