apiVersion: v2
name: pet2cattle
description: pet2cattle blog
home: https://pet2cattle.com

type: application
version: 2.1
appVersion: 3.34

sources:
- https://github.com/jordiprats/helm-pet2cattle
- https://github.com/jordiprats/flask-pet2cattle

dependencies:
  - name: minio
    version: 8.0.8
    repository: https://helm.min.io/
