{{- if .Values.ingress.redirects -}}
{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls -}}
{{- $fullName := include "pet2cattle.fullname" . -}}
{{- $shortName := include "pet2cattle.name" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-https
spec:
  entryPoints:
    - websecure
  routes:
    {{- with (first .Values.ingress.hosts) }}
    - match: Host(`{{ . }}`)
    {{- end }}
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: http
  tls:
    secretName: {{ $shortName }}-cert-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-http2s
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      priority: 1000
      kind: Rule
      services:
        - kind: TraefikService
          name: noop@internal
      middlewares:
        - name: {{ $fullName }}-http2s
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-http2s
spec:
  redirectScheme:
    scheme: https
    permanent: true
  {{- end }}
  {{- end }}
  {{- end }}