apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pet2cattle.fullname" . }}-s3sync
  labels:
    {{- include "pet2cattle-s3sync.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: 1
{{- end }}
  selector:
    matchLabels:
      {{- include "pet2cattle-s3sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "pet2cattle-s3sync.selectorLabels" . | nindent 8 }}
        component: s3sync
    spec:
      hostNetwork: {{ .Values.s3sync.hostNetwork }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-s3sync
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -xc
            - "mkdir -p $HOME/.ssh; chmod 700 $HOME/.ssh; cat /home/deploykeys/id_rsa > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa"
          volumeMounts:
            - name: home
              mountPath: /home/pet2cattle
            - name: tmp
              mountPath: /code/reposync_tmp
            {{ if not .Values.pet2cattle.s3.envAuth -}}
            - name: miniosecret
              mountPath: /etc/minio
            {{- end }}
            {{ if .Values.s3sync.key -}}
            - name: deploykeys
              mountPath: /home/deploykeys
            {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-s3sync"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/bin/sh", "/code/sync.sh" ]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if eq .Values.pet2cattle.s3.provider "Minio" }}
            - name: MINIO_URL
              {{- if .Values.minio.url }}
              value: {{ .Values.minio.url }}
              {{- else }}
              value: "http://{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000"
              {{- end }}  
            {{- end }}
            - name: MINIO_BUCKET
              value: "{{ .Values.pet2cattle.bucket.name }}"
            - name: POSTS_REPO
              value: "{{ .Values.pet2cattle.posts.repo }}"
            - name: S3_PROVIDER
              value: "{{ .Values.pet2cattle.s3.provider | default "Minio" }}"
            - name: S3_ENV_AUTH
              value: "{{ .Values.pet2cattle.s3.envAuth | default "false" }}"
            - name: S3_REGION
              value: "{{ .Values.pet2cattle.bucket.region | default "us-west-2" }}"
            - name: DEBUG
              value: "{{ .Values.pet2cattle.debug | default "" }}"
          volumeMounts:
            - name: home
              mountPath: /home/pet2cattle
            - name: tmp
              mountPath: /code/reposync_tmp
            {{ if not .Values.pet2cattle.s3.envAuth -}}
            - name: miniosecret
              mountPath: /etc/minio
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: home
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{ if not .Values.pet2cattle.s3.envAuth -}}
        - name: miniosecret
          secret:
            secretName: {{ .Release.Name }}-accesskeys
        {{- end }}
        {{- if .Values.s3sync.key }}
        - name: deploykeys
          secret:
            defaultMode: 0664
            secretName: {{ .Release.Name }}-deploykeys
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}