name: pull_container
on:
  workflow_dispatch:
  schedule:
    - cron: '54 5 */2 * *'
    - cron: '21 3 */3 * *'
    - cron: '44 19 */7 * *'

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      
      - name: check out local repo
        uses: actions/checkout@v3

      - name: Pull container
        uses: ./.github/actions/pullcontainer
        id: pullcontainer